FROM golang:1.20-alpine3.17 as build

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer .

FROM golang:1.20-alpine3.17

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /usr/src/app

COPY --from=build /build/producer .
EXPOSE 3000

CMD ["./producer"]
